### ISSUE TITLE
Feature Request: Sub Menus

### ISSUE THREAD

**Issue by RyanPWalker** [nejcm/docz-theme-extended#1]
Hi!  I think it's really cool what you've done here and will be using your theme extension!  One thing I could really use is the ability to have sub menus in the main left menu.  For example, I have several Form components with their own mdx page and I'd like to have them all in a menu under "Forms".  So the folder structure would look like `Components/Forms/Checkbox`.  
![image](https://user-images.githubusercontent.com/25303720/86954088-a335b700-c112-11ea-848b-28211e8b171a.png)

**Comment by nejcm** [comment]
Hi,

This is something I was already looking into but did not get around to implement it. 
But I saw there are people asking for it so will put it on top of my TODO list.

Cheers

**Comment by nejcm** [comment]
I had some fixes to do on the theme so I also implemented this feature. It is present in v1.9.0.
In case of any bugs open a new issue.
https://nejcm.github.io/docz-theme-extended/ui/menu#sub-menus

One thing that is not implemented yet is the sort order for sub menus.

**Comment by RyanPWalker** [comment]
That was so fast!  Thanks!
