### ISSUE TITLE
Feature Request - Props GUI

### ISSUE THREAD

**Issue by RyanPWalker** [nejcm/docz-theme-extended#11]
Something that is constantly brought up to me at my company is that they would really like a Props GUI to easily change the props in real time.  Similar to how Storybook has knobs, each props would have a "knob" corresponding to their prop type.  For example, a bool might be a checkbox, a string might be a text input, a oneOf might be a dropdown/select, a node might be an input for jsx, etc.  All of these would be in a Component similar to the Props Table.

Thoughts?  Is this doable?  It would be extremely helpful to have this.  Thank you in advance.

**Comment by nejcm** [comment]
Hi Ryan,

So regarding the requested feature I believe that Storybook is meant for exactly that purpose and they have some nice addons that allow similar documentation generation from mdx. 
This kind of feature would make more sense to be built and included in **docz** and not at the theme level. But I believe that **docz** was mostly meant for more static documentation.

You might also find a library that can be included into the mdx file that would do this kind of thing but I do not know any from the top of my head.

Best of luck. Cheers!

**Comment by RyanPWalker** [comment]
You're right, it definitely should be included in docz and not at the theme level.  However it seems docz isn't being maintained anymore.  There's been a feature request open for years that is very popular, but has gone unanswered.  So I guess I thought I'd try requesting it here.

**Comment by nejcm** [comment]
Np. The main problem for me is the time investment currently. 
I guess if you wish to continue with docz... then the best bet would be to search for a library that will do exactly what you are searching for and then plug it in into your mdx which supports react components. If you find something let me know and maybe I can also include it here if it is not too time consuming.
