### ISSUE TITLE
Running yarn dev is very slow

### ISSUE THREAD

**Issue by L-van-der-merwe** [nejcm/docz-theme-extended#12]
When I run yarn dev, it compiles the project, its very resourceful, when its done, I go to localhost:3000 and it takes 10 minutes to show the docs, when I change something, that entire process needs to be repeated, using your theme extension looks very cool and it is useful, but the duration it takes just to get a result in dev mode is really intense, wait an hour to make 6 changes. 

Any idea on what can be investigated on my environment that might be the reason for this delayed builds?

**Comment by nejcm** [comment]
Hi,

Unfortunately can't recreate this. On my side it is very performant. The first build is a bit slow (a minute or two) but after that reloads without a problem. 
Would like to see if anybody else ran into this. Will leave the issue open and lets see.

**Comment by L-van-der-merwe** [comment]
Damn, I wonder what it might be, can images have an influence in the compiling process? I want to use this theme sooo bad but it's unusable on my side, do you have a standard boilerplated version I can use to test it out before I add the theme to my current docz, if its running fine from the boilerplate, then I will move all my content over manually. 

Thanks in advance.

**Comment by nejcm** [comment]
So it's hard to say what is the performance issue. Images should not be an issue. To be honest from personal experience I had a lot of different issues in the past with npm (yarn) in general... like packages working when installed over npm but not over yarn, packages breaking after updating them... A lot of times doing a clean install helps. This means removing node_modules, doing a `yarn clean` and then reinstalling again with `yarn install`.
