### ISSUE TITLE
weird purple background color on main container.

### ISSUE THREAD

**Issue by AbdallahAbis** [nejcm/docz-theme-extended#14]
clone `docz-theme-extended` demo folder, and change `"@nejcm/docz-theme-extended": "*"` to `"@nejcm/docz-theme-extended": "^2.0.14"` so it uses the npm package instead of the local package. and run `yarn dev` and you'll notice a purple background.

![Screen Shot 2022-05-11 at 13 41 23](https://user-images.githubusercontent.com/59185227/167852473-4f45087c-a609-42df-8b4f-2fa72ba4b36a.png)

**Comment by nejcm** [comment]
Thanks for reporting. Will look into it.

**Comment by Stevemoretz** [comment]
I have the same exact issue

**Comment by nejcm** [comment]
Thanks for reporting. Will take a look.

**Comment by Stevemoretz** [comment]
> Thanks for reporting. Will take a look.


I just reinstalled everything in a new project : 

```bash
yarn add docz react react-dom @nejcm/docz-theme-extended
```

So far sounds to be like the problem is actually gone!

I'll report back if I was wrong (spoke too soon), maybe one of those package's update has fixed it.

**Comment by nejcm** [comment]
Good to hear. 
I am unable to recreate it so I believe it's probably a combination of some deps.

**Comment by wozien** [comment]
Installing theme packages from npm has style issues, but using symlinks in monorepo works fine. For example, if I copy the demo directory to a new project and start, I can reproduce the problem

**Comment by nejcm** [comment]
> Installing theme packages from npm has style issues, but using symlinks in monorepo works fine. For example, if I copy the demo directory to a new project and start, I can reproduce the problem

Will give it a try. Thanks for reporting

**Comment by nejcm** [comment]
Made a new release `v2.0.15`. Was not able to recreate the issue but I am overriding any colors set from other libraries on the container. This should fix the issue.

**Comment by nejcm** [comment]
Made a new release v2.1.0. Was not able to recreate the issue but I am overriding any colors set from other libraries on the container. This should fix the issue.
