### ISSUE TITLE
Bug: Bottom nav with sub menus

### ISSUE THREAD

**Issue by RyanPWalker** [nejcm/docz-theme-extended#3]
Using the new submenu feature, the 2 bottom navigation components show the previous/next components alphabetically instead of the previous/next components in the order of the menu+submenus.
For example, if my component is Radio under the submenu Forms, the previous component should be my NativeSelect component in the same Forms submenu and the next should be my Textarea component in the same Forms submenu.  But instead, components with the previous/next alphabetical order are shown.  Hopefully the screenshot clears up any confusion.

![image](https://user-images.githubusercontent.com/25303720/87076527-23295300-c1df-11ea-9a2f-941c95ecdc09.png)

**Comment by nejcm** [comment]
Confirmed. 

A temporary solution would be to use the ordering option for the menu from docz. inside doczrc.js (https://www.docz.site/docs/project-configuration)

But I will implement a fix for this in the next release.

**Comment by RyanPWalker** [comment]
Yep using the ordering option [like I did in the other issue](https://github.com/nejcm/docz-theme-extended/issues/2) fixed this for now.

**Comment by nejcm** [comment]
Will implement a fix for this.

**Comment by nejcm** [comment]
This was fixed in v2.0.0. See docs.

**Comment by RyanPWalker** [comment]
I can confirm from my end that the changes work.  Thanks man, I appreciate it.
