### ISSUE TITLE
subMenuGroups.some is not a function

### ISSUE THREAD

**Issue by RyanPWalker** [nejcm/docz-theme-extended#9]
When trying to use the menu search bar in the top left, I get the error: `Uncaught TypeError: subMenuGroups.some is not a function`.  I'm guessing it was just an oversight when the submenu feature was added?

Node 14.15.4
React 16.13 && React 17
Babel 7
Docz 2.3.1
@nejcm/docz-theme-extended 2.0.10

<img width="443" alt="Screenshot at Feb 05 16-13-24" src="https://user-images.githubusercontent.com/25303720/107099026-e4d43080-67cd-11eb-8f97-041dc8e43e67.png">
<img width="830" alt="Screenshot at Feb 05 16-16-42" src="https://user-images.githubusercontent.com/25303720/107099037-e867b780-67cd-11eb-8e7a-7a95dc93c506.png">

**Comment by nejcm** [comment]
Hi thanks for reporting. Will take a look into it.

**Comment by nejcm** [comment]
I pushed a fix for this. Let me know if the bug still persists. It's hard to test all the edge cases as they are many config options available. 

Cheers!

**Comment by RyanPWalker** [comment]
Looks good as far as I can tell!  Thanks for the quick turn around!!

**Comment by nejcm** [comment]
Np. Good to hear. In case of any other issues let me know.
